### ISSUE TITLE
CSR is not auto approved when --set enableSelfManagement=true

### ISSUE THREAD

**Issue by tamalsaha** [open-cluster-management-io/multicluster-controlplane#116]
I am installing mc-cp with --set enableSelfManagement=true. The CSR for the `self` cluster is created but is not auto approved. If I manually approve the csr, everything seem to work as expected.

**Comment by clyang82** [comment]
Did you have `https://github.com/open-cluster-management-io/multicluster-controlplane/blob/65996596b295e0e438f198eb728d0ebf7e449927/charts/multicluster-controlplane/values.yaml#L10` enabled in your environment?

**Comment by tamalsaha** [comment]
Yes, I am using the `ManagedClusterAutoApproval=true` feature flag but I am still seeing it.

<img width="1100" alt="Screenshot 2023-08-24 at 4 16 00 PM" src="https://github.com/open-cluster-management-io/multicluster-controlplane/assets/94814/65321b4c-2d76-401b-b0ec-72904bb7203f">

**Comment by skeeey** [comment]
I think you also need set `autoApprovalBootstrapUsers=system:admin` when you enable the self management, e.g
```
--set enableSelfManagement=true
--set autoApprovalBootstrapUsers=system:admin
```

**Comment by tamalsaha** [comment]
Thanks. This solved the issue.
