### ISSUE TITLE
fix release error

### ISSUE THREAD

**Issue by clyang82** [open-cluster-management-io/multicluster-controlplane#28]
```
Run echo "# Controlplane " > /home/runner/work/changelog.txt
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/multicluster-controlplane/multicluster-controlplane/go/src/open-cluster-management.io/multicluster-controlplane'. No such file or directory
```

**Comment by ycyaoxdu** [comment]
we refered tags during the release action https://github.com/open-cluster-management-io/multicluster-controlplane/blob/main/.github/workflows/go-release.yaml#L30, and we added first tag **after** the issue occured. 

---
https://github.com/open-cluster-management-io/multicluster-controlplane/actions/runs/3728813155/jobs/6324137591#step:4:3
